language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0
addons:
  postgresql: '9.4'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - postgresql
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - export CHROMEDRIVER_BINARY=/usr/bin/chromium-browser
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/chromium-browser --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
  - nvm install 7
  - nvm use 7
  - cd assets && npm install -g yarn && yarn && cd ..
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
