language: elixir
elixir:
  - 1.4.0
otp_release:
  - 19.0
addons:
  postgresql: '9.4'
services:
  - postgresql
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - export CHROMEDRIVER_BINARY=/usr/bin/chromium-browser
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/chromium-browser --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
  - nvm install 7
  - nvm use 7
  - cd assets && npm install -g yarn && yarn